# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b4ad2722a72a2b58781737adbcd77730129828bc5c764fa0a4ad10ea54d1d4879f3eb8e68a22e73c942f77af4815acba59811df2e12acf0fc67bc667e044d68

test:
  secret_key_base: 209a9164a81cc619befbe4459bf6024ee784fe2d0cdb1af3fab3c308e9f196b6212bdf2e2a9f5b89b055a8b0699bdabc1ba3b0aaddae3f710e8431d8959ff557

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
